# Config for the repository settings
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/configuring-repository-features-with-code

repository:
  # Enable issues in the repository
  has_issues: true

