# Repository Configuration for test-repo-mod-gamma
repository:
  # Repository Name
  name: test-repo-mod-gamma

  # Description of the repository
  description: ""

  # URL for the repository
  homepage: ""

  # Repository visibility - public or private
  visibility: public

  # Team/Individual access
  restricted_to: none

  # Enabling repository features
  features:
    issues: true
    projects: false
    wiki: false

labels:
  - name: bug
    color: "d73a4a"
    description: "Something isn't working"
  - name: documentation
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: enhancement
    color: "a2eeef"
    description: "New feature or request"
  - name: good first issue
    color: "7057ff"
    description: "Good for newcomers"
  - name: help wanted
    color: "008672"
    description: "Extra attention needed"
  - name: invalid
    color: "e4e669"
    description: "This doesn't seem right"

branches:
  # Enforce branch protection rules for main
  - name: main
    enforce_admins: on
    require_code_owner_reviews: true
    required_approving_review_count: 1